-- PL/SQL Exercises - Complete Solutions
-- Based on the uploaded exercise sheet.

------------------------------------------------------------
-- 0) Schema (from the exercise sheet)
------------------------------------------------------------
CREATE TABLE Customers (
  CustomerID   NUMBER PRIMARY KEY,
  Name         VARCHAR2(100),
  DOB          DATE,
  Balance      NUMBER,
  LastModified DATE
);

CREATE TABLE Accounts (
  AccountID    NUMBER PRIMARY KEY,
  CustomerID   NUMBER,
  AccountType  VARCHAR2(20),
  Balance      NUMBER,
  LastModified DATE,
  CONSTRAINT fk_accounts_customer FOREIGN KEY (CustomerID)
    REFERENCES Customers(CustomerID)
);

CREATE TABLE Transactions (
  TransactionID   NUMBER PRIMARY KEY,
  AccountID       NUMBER,
  TransactionDate DATE,
  Amount          NUMBER,
  TransactionType VARCHAR2(10),
  CONSTRAINT fk_transactions_account FOREIGN KEY (AccountID)
    REFERENCES Accounts(AccountID)
);

CREATE TABLE Loans (
  LoanID       NUMBER PRIMARY KEY,
  CustomerID   NUMBER,
  LoanAmount   NUMBER,
  InterestRate NUMBER,
  StartDate    DATE,
  EndDate      DATE,
  CONSTRAINT fk_loans_customer FOREIGN KEY (CustomerID)
    REFERENCES Customers(CustomerID)
);

CREATE TABLE Employees (
  EmployeeID NUMBER PRIMARY KEY,
  Name       VARCHAR2(100),
  Position   VARCHAR2(50),
  Salary     NUMBER,
  Department VARCHAR2(50),
  HireDate   DATE
);

-- Optional helper table for logging errors and audits used by solutions.
CREATE TABLE ErrorLog (
  LogID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  LogTime    DATE DEFAULT SYSDATE,
  ModuleName VARCHAR2(100),
  Message    VARCHAR2(4000)
);

CREATE TABLE AuditLog (
  AuditID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TransactionID  NUMBER,
  ActionType     VARCHAR2(50),
  ActionTime     DATE DEFAULT SYSDATE,
  Details        VARCHAR2(4000)
);

------------------------------------------------------------
-- 1) CONTROL STRUCTURES
------------------------------------------------------------

-- Scenario 1: discount loan interest rates for customers above 60
BEGIN
  FOR c IN (
    SELECT CustomerID, DOB
    FROM Customers
  ) LOOP
    IF TRUNC(MONTHS_BETWEEN(SYSDATE, c.DOB) / 12) > 60 THEN
      UPDATE Loans
      SET InterestRate = InterestRate - 1
      WHERE CustomerID = c.CustomerID;
    END IF;
  END LOOP;
  COMMIT;
END;
/

-- Scenario 2: set IsVIP for balance over 10,000
-- Assumes an IsVIP column exists; add it if needed.
-- ALTER TABLE Customers ADD IsVIP CHAR(1) DEFAULT 'N';
BEGIN
  FOR c IN (
    SELECT CustomerID, Balance
    FROM Customers
  ) LOOP
    IF c.Balance > 10000 THEN
      UPDATE Customers
      SET IsVIP = 'Y'
      WHERE CustomerID = c.CustomerID;
    ELSE
      UPDATE Customers
      SET IsVIP = 'N'
      WHERE CustomerID = c.CustomerID;
    END IF;
  END LOOP;
  COMMIT;
END;
/

-- Scenario 3: reminder for loans due in next 30 days
BEGIN
  FOR l IN (
    SELECT l.LoanID, c.Name, l.EndDate
    FROM Loans l
    JOIN Customers c ON c.CustomerID = l.CustomerID
    WHERE l.EndDate BETWEEN SYSDATE AND SYSDATE + 30
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Reminder: Loan ' || l.LoanID ||
                         ' for customer ' || l.Name ||
                         ' is due on ' || TO_CHAR(l.EndDate, 'YYYY-MM-DD'));
  END LOOP;
END;
/

------------------------------------------------------------
-- 2) ERROR HANDLING
------------------------------------------------------------

-- Scenario 1: SafeTransferFunds
CREATE OR REPLACE PROCEDURE SafeTransferFunds(
  p_from_account IN NUMBER,
  p_to_account   IN NUMBER,
  p_amount       IN NUMBER
) AS
  v_balance NUMBER;
BEGIN
  IF p_amount <= 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Transfer amount must be positive');
  END IF;

  SELECT Balance
  INTO v_balance
  FROM Accounts
  WHERE AccountID = p_from_account
  FOR UPDATE;

  IF v_balance < p_amount THEN
    RAISE_APPLICATION_ERROR(-20002, 'Insufficient funds');
  END IF;

  UPDATE Accounts
  SET Balance = Balance - p_amount,
      LastModified = SYSDATE
  WHERE AccountID = p_from_account;

  UPDATE Accounts
  SET Balance = Balance + p_amount,
      LastModified = SYSDATE
  WHERE AccountID = p_to_account;

  INSERT INTO Transactions(TransactionID, AccountID, TransactionDate, Amount, TransactionType)
  VALUES ((SELECT NVL(MAX(TransactionID),0)+1 FROM Transactions), p_from_account, SYSDATE, p_amount, 'Withdrawal');

  INSERT INTO Transactions(TransactionID, AccountID, TransactionDate, Amount, TransactionType)
  VALUES ((SELECT NVL(MAX(TransactionID),0)+1 FROM Transactions), p_to_account, SYSDATE, p_amount, 'Deposit');

  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ErrorLog(ModuleName, Message)
    VALUES ('SafeTransferFunds', 'Account not found');
    ROLLBACK;
  WHEN OTHERS THEN
    INSERT INTO ErrorLog(ModuleName, Message)
    VALUES ('SafeTransferFunds', SQLERRM);
    ROLLBACK;
    RAISE;
END;
/

-- Scenario 2: UpdateSalary
CREATE OR REPLACE PROCEDURE UpdateSalary(
  p_employee_id IN NUMBER,
  p_percent     IN NUMBER
) AS
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
  FROM Employees
  WHERE EmployeeID = p_employee_id;

  IF v_exists = 0 THEN
    RAISE_APPLICATION_ERROR(-20010, 'Employee ID does not exist');
  END IF;

  UPDATE Employees
  SET Salary = Salary + (Salary * p_percent / 100)
  WHERE EmployeeID = p_employee_id;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    INSERT INTO ErrorLog(ModuleName, Message)
    VALUES ('UpdateSalary', SQLERRM);
    ROLLBACK;
END;
/

-- Scenario 3: AddNewCustomer
CREATE OR REPLACE PROCEDURE AddNewCustomer(
  p_customer_id IN NUMBER,
  p_name        IN VARCHAR2,
  p_dob         IN DATE,
  p_balance     IN NUMBER
) AS
BEGIN
  INSERT INTO Customers(CustomerID, Name, DOB, Balance, LastModified)
  VALUES (p_customer_id, p_name, p_dob, p_balance, SYSDATE);
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    INSERT INTO ErrorLog(ModuleName, Message)
    VALUES ('AddNewCustomer', 'Customer with same ID already exists');
    ROLLBACK;
  WHEN OTHERS THEN
    INSERT INTO ErrorLog(ModuleName, Message)
    VALUES ('AddNewCustomer', SQLERRM);
    ROLLBACK;
END;
/

------------------------------------------------------------
-- 3) STORED PROCEDURES
------------------------------------------------------------

-- Scenario 1: ProcessMonthlyInterest
CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest AS
BEGIN
  UPDATE Accounts
  SET Balance = Balance * 1.01,
      LastModified = SYSDATE
  WHERE AccountType = 'Savings';

  COMMIT;
END;
/

-- Scenario 2: UpdateEmployeeBonus
CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(
  p_department    IN VARCHAR2,
  p_bonus_percent IN NUMBER
) AS
BEGIN
  UPDATE Employees
  SET Salary = Salary + (Salary * p_bonus_percent / 100)
  WHERE Department = p_department;

  COMMIT;
END;
/

-- Scenario 3: TransferFunds
CREATE OR REPLACE PROCEDURE TransferFunds(
  p_from_account IN NUMBER,
  p_to_account   IN NUMBER,
  p_amount       IN NUMBER
) AS
  v_balance NUMBER;
BEGIN
  SELECT Balance INTO v_balance
  FROM Accounts
  WHERE AccountID = p_from_account
  FOR UPDATE;

  IF v_balance < p_amount THEN
    RAISE_APPLICATION_ERROR(-20020, 'Insufficient balance');
  END IF;

  UPDATE Accounts
  SET Balance = Balance - p_amount,
      LastModified = SYSDATE
  WHERE AccountID = p_from_account;

  UPDATE Accounts
  SET Balance = Balance + p_amount,
      LastModified = SYSDATE
  WHERE AccountID = p_to_account;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

------------------------------------------------------------
-- 4) FUNCTIONS
------------------------------------------------------------

-- Scenario 1: CalculateAge
CREATE OR REPLACE FUNCTION CalculateAge(
  p_dob IN DATE
) RETURN NUMBER IS
BEGIN
  RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, p_dob) / 12);
END;
/

-- Scenario 2: CalculateMonthlyInstallment
CREATE OR REPLACE FUNCTION CalculateMonthlyInstallment(
  p_loan_amount   IN NUMBER,
  p_interest_rate IN NUMBER,
  p_years         IN NUMBER
) RETURN NUMBER IS
  v_monthly_rate NUMBER := (p_interest_rate / 100) / 12;
  v_months       NUMBER := p_years * 12;
BEGIN
  IF v_monthly_rate = 0 THEN
    RETURN p_loan_amount / v_months;
  END IF;

  RETURN (p_loan_amount * v_monthly_rate * POWER(1 + v_monthly_rate, v_months)) /
         (POWER(1 + v_monthly_rate, v_months) - 1);
END;
/

-- Scenario 3: HasSufficientBalance
CREATE OR REPLACE FUNCTION HasSufficientBalance(
  p_account_id IN NUMBER,
  p_amount     IN NUMBER
) RETURN NUMBER IS
  v_balance NUMBER;
BEGIN
  SELECT Balance INTO v_balance
  FROM Accounts
  WHERE AccountID = p_account_id;

  IF v_balance >= p_amount THEN
    RETURN 1;
  ELSE
    RETURN 0;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

------------------------------------------------------------
-- 5) TRIGGERS
------------------------------------------------------------

-- Scenario 1: update last modified on customer update
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
  :NEW.LastModified := SYSDATE;
END;
/

-- Scenario 2: audit log for all transactions
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
  INSERT INTO AuditLog(TransactionID, ActionType, ActionTime, Details)
  VALUES (:NEW.TransactionID, 'INSERT', SYSDATE,
          'Transaction ' || :NEW.TransactionType || ' of amount ' || :NEW.Amount);
END;
/

-- Scenario 3: enforce deposit/withdrawal business rules
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
  v_balance NUMBER;
BEGIN
  IF :NEW.TransactionType = 'Deposit' THEN
    IF :NEW.Amount <= 0 THEN
      RAISE_APPLICATION_ERROR(-20030, 'Deposit amount must be positive');
    END IF;
  ELSIF :NEW.TransactionType = 'Withdrawal' THEN
    IF :NEW.Amount <= 0 THEN
      RAISE_APPLICATION_ERROR(-20031, 'Withdrawal amount must be positive');
    END IF;

    SELECT Balance INTO v_balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF v_balance < :NEW.Amount THEN
      RAISE_APPLICATION_ERROR(-20032, 'Withdrawal exceeds available balance');
    END IF;
  END IF;
END;
/

------------------------------------------------------------
-- 6) CURSORS
------------------------------------------------------------

-- Scenario 1: GenerateMonthlyStatements
DECLARE
  CURSOR c_stmt IS
    SELECT c.CustomerID, c.Name, t.TransactionID, t.TransactionDate, t.Amount, t.TransactionType
    FROM Customers c
    JOIN Accounts a ON a.CustomerID = c.CustomerID
    JOIN Transactions t ON t.AccountID = a.AccountID
    WHERE TRUNC(t.TransactionDate, 'MM') = TRUNC(SYSDATE, 'MM')
    ORDER BY c.CustomerID, t.TransactionDate;

  v_prev_customer NUMBER := NULL;
BEGIN
  FOR r IN c_stmt LOOP
    IF v_prev_customer IS NULL OR v_prev_customer <> r.CustomerID THEN
      DBMS_OUTPUT.PUT_LINE('Statement for Customer ' || r.CustomerID || ' - ' || r.Name);
      v_prev_customer := r.CustomerID;
    END IF;
    DBMS_OUTPUT.PUT_LINE('  Txn ' || r.TransactionID || ' | ' ||
                         TO_CHAR(r.TransactionDate, 'YYYY-MM-DD') || ' | ' ||
                         r.TransactionType || ' | ' || r.Amount);
  END LOOP;
END;
/

-- Scenario 2: ApplyAnnualFee
DECLARE
  CURSOR c_acc IS
    SELECT AccountID, Balance
    FROM Accounts
    FOR UPDATE;
BEGIN
  FOR r IN c_acc LOOP
    UPDATE Accounts
    SET Balance = Balance - 100,
        LastModified = SYSDATE
    WHERE CURRENT OF c_acc;
  END LOOP;
  COMMIT;
END;
/

-- Scenario 3: UpdateLoanInterestRates
DECLARE
  CURSOR c_loan IS
    SELECT LoanID, InterestRate
    FROM Loans
    FOR UPDATE;
BEGIN
  FOR r IN c_loan LOOP
    UPDATE Loans
    SET InterestRate = InterestRate + 0.5
    WHERE CURRENT OF c_loan;
  END LOOP;
  COMMIT;
END;
/

------------------------------------------------------------
-- 7) PACKAGES
------------------------------------------------------------

-- 7A) CustomerManagement package
CREATE OR REPLACE PACKAGE CustomerManagement AS
  PROCEDURE AddCustomer(
    p_customer_id IN NUMBER,
    p_name        IN VARCHAR2,
    p_dob         IN DATE,
    p_balance     IN NUMBER
  );

  PROCEDURE UpdateCustomerDetails(
    p_customer_id IN NUMBER,
    p_name        IN VARCHAR2,
    p_balance     IN NUMBER
  );

  FUNCTION GetCustomerBalance(
    p_customer_id IN NUMBER
  ) RETURN NUMBER;
END CustomerManagement;
/

CREATE OR REPLACE PACKAGE BODY CustomerManagement AS
  PROCEDURE AddCustomer(
    p_customer_id IN NUMBER,
    p_name        IN VARCHAR2,
    p_dob         IN DATE,
    p_balance     IN NUMBER
  ) AS
  BEGIN
    INSERT INTO Customers(CustomerID, Name, DOB, Balance, LastModified)
    VALUES (p_customer_id, p_name, p_dob, p_balance, SYSDATE);
  END;

  PROCEDURE UpdateCustomerDetails(
    p_customer_id IN NUMBER,
    p_name        IN VARCHAR2,
    p_balance     IN NUMBER
  ) AS
  BEGIN
    UPDATE Customers
    SET Name = p_name,
        Balance = p_balance,
        LastModified = SYSDATE
    WHERE CustomerID = p_customer_id;
  END;

  FUNCTION GetCustomerBalance(
    p_customer_id IN NUMBER
  ) RETURN NUMBER IS
    v_balance NUMBER;
  BEGIN
    SELECT Balance INTO v_balance
    FROM Customers
    WHERE CustomerID = p_customer_id;
    RETURN v_balance;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END;
END CustomerManagement;
/

-- 7B) EmployeeManagement package
CREATE OR REPLACE PACKAGE EmployeeManagement AS
  PROCEDURE HireEmployee(
    p_employee_id IN NUMBER,
    p_name        IN VARCHAR2,
    p_position    IN VARCHAR2,
    p_salary      IN NUMBER,
    p_department  IN VARCHAR2,
    p_hiredate    IN DATE
  );

  PROCEDURE UpdateEmployeeDetails(
    p_employee_id IN NUMBER,
    p_position    IN VARCHAR2,
    p_salary      IN NUMBER,
    p_department  IN VARCHAR2
  );

  FUNCTION CalculateAnnualSalary(
    p_employee_id IN NUMBER
  ) RETURN NUMBER;
END EmployeeManagement;
/

CREATE OR REPLACE PACKAGE BODY EmployeeManagement AS
  PROCEDURE HireEmployee(
    p_employee_id IN NUMBER,
    p_name        IN VARCHAR2,
    p_position    IN VARCHAR2,
    p_salary      IN NUMBER,
    p_department  IN VARCHAR2,
    p_hiredate    IN DATE
  ) AS
  BEGIN
    INSERT INTO Employees(EmployeeID, Name, Position, Salary, Department, HireDate)
    VALUES (p_employee_id, p_name, p_position, p_salary, p_department, p_hiredate);
  END;

  PROCEDURE UpdateEmployeeDetails(
    p_employee_id IN NUMBER,
    p_position    IN VARCHAR2,
    p_salary      IN NUMBER,
    p_department  IN VARCHAR2
  ) AS
  BEGIN
    UPDATE Employees
    SET Position = p_position,
        Salary = p_salary,
        Department = p_department
    WHERE EmployeeID = p_employee_id;
  END;

  FUNCTION CalculateAnnualSalary(
    p_employee_id IN NUMBER
  ) RETURN NUMBER IS
    v_salary NUMBER;
  BEGIN
    SELECT Salary INTO v_salary
    FROM Employees
    WHERE EmployeeID = p_employee_id;
    RETURN v_salary * 12;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END;
END EmployeeManagement;
/

-- 7C) AccountOperations package
CREATE OR REPLACE PACKAGE AccountOperations AS
  PROCEDURE OpenAccount(
    p_account_id   IN NUMBER,
    p_customer_id  IN NUMBER,
    p_account_type IN VARCHAR2,
    p_balance      IN NUMBER
  );

  PROCEDURE CloseAccount(
    p_account_id IN NUMBER
  );

  FUNCTION GetTotalBalance(
    p_customer_id IN NUMBER
  ) RETURN NUMBER;
END AccountOperations;
/

CREATE OR REPLACE PACKAGE BODY AccountOperations AS
  PROCEDURE OpenAccount(
    p_account_id   IN NUMBER,
    p_customer_id  IN NUMBER,
    p_account_type IN VARCHAR2,
    p_balance      IN NUMBER
  ) AS
  BEGIN
    INSERT INTO Accounts(AccountID, CustomerID, AccountType, Balance, LastModified)
    VALUES (p_account_id, p_customer_id, p_account_type, p_balance, SYSDATE);
  END;

  PROCEDURE CloseAccount(
    p_account_id IN NUMBER
  ) AS
  BEGIN
    DELETE FROM Accounts
    WHERE AccountID = p_account_id;
  END;

  FUNCTION GetTotalBalance(
    p_customer_id IN NUMBER
  ) RETURN NUMBER IS
    v_total NUMBER;
  BEGIN
    SELECT NVL(SUM(Balance), 0)
    INTO v_total
    FROM Accounts
    WHERE CustomerID = p_customer_id;
    RETURN v_total;
  END;
END AccountOperations;
/

------------------------------------------------------------
-- End of file
------------------------------------------------------------
